/**
 * U3 — ReportPreview extraction contract.
 * ─────────────────────────────────────────────────────────────────────────────
 * docs/PLAN-ADMIN-MODAL-UNIFICATION-2026-07.md — PR-U3.
 *
 * The preview + record-edit cluster moved 1:1 out of ClientReportModal into ReportPreview.
 * This suite pins the move's invariants + the 3 declared changes so a regression is caught:
 *   - the updateTimesheetEntry write payload is BYTE-IDENTICAL (only the file changed),
 *   - z-index bumped 10001/10002/10003 → 10600/10610/10620 (DA-4),
 *   - SEC-1 escape-at-sink on the two previously-unescaped innerHTML sinks,
 *   - fix#2: the preview no longer closes the host modal, and closePreview no longer reopens,
 *   - ClientReportModal keeps thin delegates; the host copy of the cluster is gone (no dup).
 *
 * Plus light behavioral coverage of the two moved methods that need no host/firebase stubs
 * (formatDate = pure; closePreview = overlay-only DOM).
 */
import * as fs from 'fs';
import * as path from 'path';

import { describe, it, expect } from 'vitest';

// No globals are needed at import (no method runs on load); stub escapeHtml defensively.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
(window as any).escapeHtml = (s: unknown): string => (s === null || s === undefined ? '' : String(s));

// @ts-ignore — classic admin-panel script, no type declarations
import '../../../apps/admin-panel/js/ui/ReportPreview.js';

const ADMIN = path.resolve(__dirname, '../../../apps/admin-panel');
const read = (rel: string): string => fs.readFileSync(path.resolve(ADMIN, rel), 'utf8');
const PREVIEW = read('js/ui/ReportPreview.js');
const REPORT = read('js/ui/ClientReportModal.js');

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const inst = (window as any).ReportPreview;

// ── the write payload survived the move byte-identically ─────────────────────
describe('U3 · updateTimesheetEntry payload is byte-identical in the new file', () => {
  it('calls the same CF with the same 9-field payload + editHistory/autoGenerated', () => {
    expect(PREVIEW).toContain("httpsCallable('updateTimesheetEntry')");
    for (const field of [
      'entryId: entryId', 'date: currentEntry.date', 'minutes: minutes', 'action: action',
      'editHistory: editHistory', 'taskId: currentEntry.taskId || null',
      'autoGenerated: currentEntry.autoGenerated || false',
      'clientId: currentEntry.clientId || clientId || null',
      'serviceId: currentEntry.serviceId || currentEntry.service || null'
    ]) {
      expect(PREVIEW, field).toContain(field);
    }
  });
  it('the host no longer contains the write (moved, not duplicated)', () => {
    expect(REPORT).not.toContain("httpsCallable('updateTimesheetEntry')");
    expect(REPORT).not.toMatch(/renderTimesheetPreviewModal\s*\(reportData/);
  });
});

// ── DA-4: z-index layers bumped above the unified modal (10200) + status (10500) ─
describe('U3 · z-index overlays moved to the 10600 band', () => {
  it('preview 10600 / edit 10610 / toast 10620 present; old 10001/10002/10003 gone', () => {
    expect(PREVIEW).toContain('z-index: 10600');
    expect(PREVIEW).toContain('z-index: 10610');
    expect(PREVIEW).toContain('z-index: 10620');
    expect(PREVIEW).not.toContain('z-index: 10001');
    expect(PREVIEW).not.toContain('z-index: 10002');
    expect(PREVIEW).not.toContain('z-index: 10003');
  });
});

// ── SEC-1: the two previously-unescaped innerHTML sinks are escaped at the sink ─
describe('U3 · SEC-1 escape-at-sink on the two innerHTML sinks', () => {
  it('the preview header clientName is routed through window.escapeHtml', () => {
    expect(PREVIEW).toContain('${window.escapeHtml(clientName)}');
  });
  it('the toast message (carries a server error.message) is routed through window.escapeHtml', () => {
    expect(PREVIEW).toContain('${window.escapeHtml(message)}');
  });
});

// ── fix#2: preview overlays on open; proceed closes the host on success ───────
describe('U3 · fix#2 — overlay-on-open, no reopen, close-on-successful-generate', () => {
  it('closePreview only removes its overlay — never reopens', () => {
    expect(PREVIEW, 'closePreview must not reopen anything').not.toMatch(/\.open\(/);
  });
  it('proceedToGenerateReport closes the host modal AFTER a successful generate (clean end-state)', () => {
    // fix#2 keeps the host open only while the preview overlays it; completing the report
    // is the natural close point (restores the pre-move end-state). On error it stays open.
    expect(PREVIEW).toMatch(/proceedToGenerateReport[\s\S]*?ReportGenerator\.generate[\s\S]*?h\.close\(\)/);
  });
});

// ── delegates: the host routes the entry points to ReportPreview ─────────────
describe('U7 · ClientReportModal is a thin shim — only the edit-timesheet delegate survives', () => {
  // U7 (delete-last) gutted the standalone modal: the preview/generate/email flow moved to
  // the unified report tab (ReportTab → ReportPreview/ReportGenerator). The shim keeps ONE
  // delegate — openEditTimesheetModal → ReportPreview.openEditModal (ReportGenerator still calls it).
  it.each([
    'window.ReportPreview.openEditModal(entryData)'
  ])('shim delegate: %s', (call) => {
    expect(REPORT).toContain(call);
  });
  it('the retired preview/generate delegates are gone from the shim', () => {
    expect(REPORT).not.toContain('window.ReportPreview.showTimesheetPreview()');
    expect(REPORT).not.toContain('window.ReportPreview.proceedToGenerateReport()');
  });
  it('the in-preview onclicks point at ReportPreview, not the old ClientReportModal', () => {
    expect(PREVIEW).toContain('onclick="window.ReportPreview.closePreview()"');
    expect(PREVIEW).toContain('onclick="window.ReportPreview.proceedToGenerateReport()"');
    expect(PREVIEW).not.toContain('window.ClientReportModal.closePreview');
  });
  it('the email flow moved OFF the host to ReportTab (U6/U7) — the shim does not carry it', () => {
    expect(REPORT).not.toContain('generateAndEmailReport');
    expect(REPORT).not.toContain('window.ReportGenerator.generateAndEmail');
  });
});

// ── light behavioral: the two host/firebase-free moved methods ───────────────
describe('U3 · behavioral (no host/firebase needed)', () => {
  it('formatDate handles string / Date / null', () => {
    expect(inst.formatDate('2026-08-02')).toBe('02/08/2026');
    expect(inst.formatDate(new Date(2026, 7, 2))).toBe('02/08/2026'); // month is 0-based
    expect(inst.formatDate(null)).toBe('-');
    expect(inst.formatDate(undefined)).toBe('-');
  });
  it('closePreview removes ONLY the overlay (fix#2 — no reopen, no throw)', () => {
    document.body.innerHTML =
      '<div id="clientReportModal"></div><div id="timesheetPreviewOverlay"></div>';
    expect(() => inst.closePreview()).not.toThrow();
    expect(document.getElementById('timesheetPreviewOverlay')).toBeNull();
    // the host modal element is untouched (it was never closed to show the preview).
    expect(document.getElementById('clientReportModal')).not.toBeNull();
  });
});
