/**
 * CHARACTERIZATION goldens — updateTimesheetEntry validation + write payload +
 * editHistory normalization + auth + error contract (timesheet/index.js:1327).
 *
 * updateTimesheetEntry's −10h overdraft GUARD (increase blocked below −10h across
 * hours / legal_procedure service types) is already covered by tests/update-guard.test.js.
 * This suite pins the parts that focus does NOT assert — so a future JS→TS rewrite of
 * timesheet/index.js can't silently drift them. It asserts what the code DOES today,
 * not what it "should" do.
 *
 * Pinned:
 *   1. the 5 pre-transaction input guards (entryId / date / valid-date / positive-number
 *      minutes / editHistory-is-array), each → HttpsError('invalid-argument', <Hebrew>).
 *   2. auth: entry-not-found → 'not-found'; a non-admin editing SOMEONE ELSE'S entry →
 *      'permission-denied' (no write); an admin may edit anyone's entry.
 *   3. the entry-doc update payload: date normalized to YMD, minutes verbatim,
 *      hours = minutes/60, lastEditedBy = user.username, lastEditedAt = serverTimestamp,
 *      and `action` written ONLY when data.action !== undefined.
 *   4. editHistory timestamp normalization (the 4 branches): ISO string → Timestamp.fromDate;
 *      a serverTimestamp placeholder → Timestamp.now(); an existing {seconds,nanoseconds} →
 *      passed through UNCHANGED; anything else → Timestamp.now().
 *   5. the task-mirror write (autoGenerated + taskId): task.timeEntries[entryId] gets
 *      minutes/hours/action refreshed, non-matching entries untouched, lastActivity stamped.
 *   6. catch contract: an HttpsError is rethrown verbatim; any other error →
 *      HttpsError('internal', 'שגיאה בעדכון רשומת שעתון: …').
 *
 * Harness mirrors tests/update-guard.test.js (same SDK-boundary mock set that mounts the
 * whole timesheet/index.js require graph — the rest loads as real modules, incl. the REAL
 * shared/calendar normalizeDateToYMD), with the doc refs _collection-tagged so the entry
 * write and the task write can be told apart. To stay OFF the −10h guard path (covered
 * elsewhere) the tests pass NO data.clientId → clientDoc2 is null → the blocked-service +
 * overdraft blocks are skipped. test/setup.js is untouched.
 */

// ═══════════════════════════════════════════════════════════════
// Mocks — must precede require()
// ═══════════════════════════════════════════════════════════════

const mockTransaction = { get: jest.fn(), set: jest.fn(), update: jest.fn() };
const mockRunTransaction = jest.fn(async (fn) => fn(mockTransaction));

function makeRef(name, id) {
  return {
    id,
    _collection: name,
    collection: jest.fn(() => ({ doc: jest.fn(() => ({ id: 'auto_id' })) }))
  };
}

const mockDb = {
  collection: jest.fn((name) => ({
    _collection: name,
    doc: jest.fn((id) => makeRef(name, id)),
    where: jest.fn(() => ({ get: jest.fn().mockResolvedValue({ forEach: jest.fn() }) }))
  })),
  runTransaction: mockRunTransaction
};

jest.mock('firebase-admin', () => ({
  initializeApp: jest.fn(),
  firestore: Object.assign(() => mockDb, {
    FieldValue: {
      serverTimestamp: jest.fn(() => 'SERVER_TIMESTAMP'),
      increment: jest.fn((n) => ({ _increment: n })),
      arrayUnion: jest.fn((...args) => ({ _arrayUnion: args }))
    },
    Timestamp: {
      now: jest.fn(() => ({ seconds: 1700000000, nanoseconds: 0 })),
      fromDate: jest.fn((d) => ({ seconds: Math.floor(d.getTime() / 1000), nanoseconds: 0 }))
    }
  })
}));

jest.mock('firebase-functions', () => ({
  https: {
    HttpsError: class HttpsError extends Error {
      constructor(code, message, details) {
        super(message);
        this.code = code;
        this.details = details;
      }
    },
    onCall: jest.fn((fn) => fn)
  },
  logger: { info: jest.fn(), warn: jest.fn(), error: jest.fn() }
}));

jest.mock('firebase-functions/v2/firestore', () => ({
  onDocumentWritten: jest.fn(() => jest.fn())
}));

jest.mock('../shared/auth', () => ({ checkUserPermissions: jest.fn() }));
jest.mock('../shared/audit', () => ({ logAction: jest.fn().mockResolvedValue(undefined) }));
jest.mock('../shared/validators', () => ({
  sanitizeString: jest.fn((s) => s),
  getDescriptionLimit: jest.fn().mockResolvedValue(1000)
}));

// ═══════════════════════════════════════════════════════════════
// Imports
// ═══════════════════════════════════════════════════════════════

const { updateTimesheetEntry } = require('../timesheet/index');
const { checkUserPermissions } = require('../shared/auth');
const { https } = require('firebase-functions');

// ─── fixtures ──────────────────────────────────────────────────

const EMPLOYEE_USER = { uid: 'u1', email: 'user@test.com', username: 'user', role: 'employee' };
const ADMIN_USER = { uid: 'a1', email: 'admin@test.com', username: 'admin', role: 'admin' };

const ISO = '2026-01-01T00:00:00.000Z';

function makeEntryDoc(overrides = {}) {
  return {
    exists: true,
    data: () => ({
      clientId: 'C001', serviceId: 'svc_1', packageId: 'pkg_1',
      date: '2026-03-01', minutes: 60, hours: 1, action: 'עבודה',
      employee: 'user@test.com', ...overrides
    })
  };
}

// Valid input that stays OFF the -10h guard path (no data.clientId → clientDoc2 null).
function baseData(overrides = {}) {
  return { entryId: 'e1', date: '2026-04-01', minutes: 90, editHistory: [{ editedBy: 'user', editedAt: ISO }], ...overrides };
}

function entryUpdates() {
  return mockTransaction.update.mock.calls.filter(([ref]) => ref && ref._collection === 'timesheet_entries');
}
function taskUpdates() {
  return mockTransaction.update.mock.calls.filter(([ref]) => ref && ref._collection === 'budget_tasks');
}

beforeEach(() => {
  jest.clearAllMocks();
  mockTransaction.get.mockReset();
  mockTransaction.set.mockReset();
  mockTransaction.update.mockReset();
  mockRunTransaction.mockImplementation(async (fn) => fn(mockTransaction));
  checkUserPermissions.mockReset();
  checkUserPermissions.mockResolvedValue({ ...EMPLOYEE_USER }); // default: non-admin, owns the entry
});

// ════════════════════════════════════════════════════════════════
// input validation — 5 guards, all BEFORE the transaction
// ════════════════════════════════════════════════════════════════

describe('updateTimesheetEntry — input validation (characterization)', () => {

  test('missing entryId → invalid-argument חסר מזהה רשומה', async () => {
    await expect(updateTimesheetEntry({ date: '2026-04-01', minutes: 90, editHistory: [] }, {}))
      .rejects.toMatchObject({ code: 'invalid-argument', message: 'חסר מזהה רשומה' });
    expect(mockTransaction.update).not.toHaveBeenCalled();
  });

  test('missing date → invalid-argument חסר תאריך', async () => {
    await expect(updateTimesheetEntry({ entryId: 'e1', minutes: 90, editHistory: [] }, {}))
      .rejects.toMatchObject({ code: 'invalid-argument', message: 'חסר תאריך' });
  });

  test('unparseable date → invalid-argument (normalizeDateToYMD message surfaced)', async () => {
    await expect(updateTimesheetEntry({ entryId: 'e1', date: 'not-a-date', minutes: 90, editHistory: [] }, {}))
      .rejects.toMatchObject({ code: 'invalid-argument', message: expect.stringContaining('invalid date string') });
  });

  test('minutes must be a positive NUMBER: 0 and the string "90" both rejected', async () => {
    await expect(updateTimesheetEntry(baseData({ minutes: 0 }), {}))
      .rejects.toMatchObject({ code: 'invalid-argument', message: 'דקות חייבות להיות מספר חיובי' });
    // QUIRK: a numeric STRING fails the `typeof !== 'number'` half of the guard
    await expect(updateTimesheetEntry(baseData({ minutes: '90' }), {}))
      .rejects.toMatchObject({ code: 'invalid-argument', message: 'דקות חייבות להיות מספר חיובי' });
  });

  test('editHistory missing or non-array → invalid-argument חסרה היסטוריית עריכה', async () => {
    await expect(updateTimesheetEntry({ entryId: 'e1', date: '2026-04-01', minutes: 90 }, {}))
      .rejects.toMatchObject({ code: 'invalid-argument', message: 'חסרה היסטוריית עריכה' });
    await expect(updateTimesheetEntry(baseData({ editHistory: 'x' }), {}))
      .rejects.toMatchObject({ code: 'invalid-argument', message: 'חסרה היסטוריית עריכה' });
  });
});

// ════════════════════════════════════════════════════════════════
// authorization + existence (inside the transaction)
// ════════════════════════════════════════════════════════════════

describe('updateTimesheetEntry — auth + existence (characterization)', () => {

  test('entry not found → not-found רשומת שעתון לא נמצאה', async () => {
    mockTransaction.get.mockResolvedValueOnce({ exists: false });
    await expect(updateTimesheetEntry(baseData(), {}))
      .rejects.toMatchObject({ code: 'not-found', message: 'רשומת שעתון לא נמצאה' });
    expect(entryUpdates()).toHaveLength(0);
  });

  test('non-admin editing SOMEONE ELSE\'S entry → permission-denied (no write)', async () => {
    checkUserPermissions.mockResolvedValueOnce({ ...EMPLOYEE_USER, email: 'intruder@test.com' });
    mockTransaction.get.mockResolvedValueOnce(makeEntryDoc({ employee: 'owner@test.com' }));
    await expect(updateTimesheetEntry(baseData(), {}))
      .rejects.toMatchObject({ code: 'permission-denied', message: 'אין הרשאה לערוך רשומה זו' });
    expect(entryUpdates()).toHaveLength(0);
  });

  test('admin may edit ANYONE\'S entry → write proceeds', async () => {
    checkUserPermissions.mockResolvedValueOnce({ ...ADMIN_USER });
    mockTransaction.get.mockResolvedValueOnce(makeEntryDoc({ employee: 'someoneelse@test.com' }));
    const result = await updateTimesheetEntry(baseData(), {});
    expect(result).toEqual({ success: true, entryId: 'e1' });
    expect(entryUpdates()).toHaveLength(1);
  });
});

// ════════════════════════════════════════════════════════════════
// entry-doc write payload (characterization)
// ════════════════════════════════════════════════════════════════

describe('updateTimesheetEntry — entry write payload (characterization)', () => {

  test('payload: normalized date, minutes, hours=minutes/60, lastEditedBy=username, serverTimestamp; NO action when omitted', async () => {
    mockTransaction.get.mockResolvedValueOnce(makeEntryDoc());
    const result = await updateTimesheetEntry(baseData(), {});

    expect(result).toEqual({ success: true, entryId: 'e1' });
    const payload = entryUpdates()[0][1];
    expect(payload).toMatchObject({
      date: '2026-04-01',
      minutes: 90,
      hours: 1.5,                     // minutes / 60
      lastEditedAt: 'SERVER_TIMESTAMP',
      lastEditedBy: 'user'            // user.username
    });
    // action is set ONLY when data.action !== undefined
    expect(payload).not.toHaveProperty('action');
  });

  test('action written verbatim when provided', async () => {
    mockTransaction.get.mockResolvedValueOnce(makeEntryDoc());
    await updateTimesheetEntry(baseData({ action: 'פגישה' }), {});
    expect(entryUpdates()[0][1].action).toBe('פגישה');
  });
});

// ════════════════════════════════════════════════════════════════
// editHistory timestamp normalization (the 4 branches)
// ════════════════════════════════════════════════════════════════

describe('updateTimesheetEntry — editHistory normalization (characterization)', () => {

  test('ISO string editedAt → Timestamp.fromDate; sibling fields preserved', async () => {
    mockTransaction.get.mockResolvedValueOnce(makeEntryDoc());
    await updateTimesheetEntry(baseData({ editHistory: [{ editedBy: 'u', editedAt: ISO }] }), {});
    const eh = entryUpdates()[0][1].editHistory;
    expect(eh[0].editedAt).toEqual({ seconds: Math.floor(Date.parse(ISO) / 1000), nanoseconds: 0 });
    expect(eh[0].editedBy).toBe('u');
  });

  test('serverTimestamp placeholder editedAt → Timestamp.now()', async () => {
    mockTransaction.get.mockResolvedValueOnce(makeEntryDoc());
    await updateTimesheetEntry(baseData({ editHistory: [{ editedAt: { _methodName: 'FieldValue.serverTimestamp' } }] }), {});
    expect(entryUpdates()[0][1].editHistory[0].editedAt).toEqual({ seconds: 1700000000, nanoseconds: 0 });
  });

  test('an existing {seconds,nanoseconds} editedAt is passed through UNCHANGED', async () => {
    mockTransaction.get.mockResolvedValueOnce(makeEntryDoc());
    const ts = { seconds: 123, nanoseconds: 456 };
    await updateTimesheetEntry(baseData({ editHistory: [{ editedAt: ts }] }), {});
    expect(entryUpdates()[0][1].editHistory[0].editedAt).toEqual(ts);
  });

  test('QUIRK: an unrecognized editedAt (e.g. a number) → Timestamp.now()', async () => {
    mockTransaction.get.mockResolvedValueOnce(makeEntryDoc());
    await updateTimesheetEntry(baseData({ editHistory: [{ editedAt: 12345 }] }), {});
    expect(entryUpdates()[0][1].editHistory[0].editedAt).toEqual({ seconds: 1700000000, nanoseconds: 0 });
  });
});

// ════════════════════════════════════════════════════════════════
// task mirror write (autoGenerated + taskId)
// ════════════════════════════════════════════════════════════════

describe('updateTimesheetEntry — task.timeEntries mirror (characterization)', () => {

  test('matching entryId in task.timeEntries is refreshed; others untouched; lastActivity stamped', async () => {
    mockTransaction.get.mockResolvedValueOnce(makeEntryDoc());              // entryDoc
    mockTransaction.get.mockResolvedValueOnce({                            // taskDoc (autoGenerated → read)
      exists: true,
      data: () => ({
        timeEntries: [
          { entryId: 'e1', minutes: 60, hours: 1, action: 'עבודה' },
          { entryId: 'other', minutes: 30, hours: 0.5, action: 'משהו' }
        ]
      })
    });

    const result = await updateTimesheetEntry(baseData({ taskId: 't1', autoGenerated: true }), {});
    expect(result.success).toBe(true);

    const taskPayload = taskUpdates()[0][1];
    expect(taskPayload.lastActivity).toBe('SERVER_TIMESTAMP');

    const refreshed = taskPayload.timeEntries.find((e) => e.entryId === 'e1');
    expect(refreshed).toMatchObject({
      entryId: 'e1',
      minutes: 90,
      hours: 1.5,
      action: 'עבודה',                 // data.action omitted → falls back to entry.action
      lastEditedAt: 'SERVER_TIMESTAMP'
    });
    // the non-matching entry is left as-is
    expect(taskPayload.timeEntries.find((e) => e.entryId === 'other')).toEqual({
      entryId: 'other', minutes: 30, hours: 0.5, action: 'משהו'
    });
  });
});

// ════════════════════════════════════════════════════════════════
// error contract (characterization)
// ════════════════════════════════════════════════════════════════

describe('updateTimesheetEntry — error contract (characterization)', () => {

  test('QUIRK: a non-HttpsError is wrapped as HttpsError(internal) with a Hebrew message', async () => {
    mockTransaction.get.mockResolvedValueOnce(makeEntryDoc());
    mockTransaction.update.mockImplementationOnce(() => { throw new Error('boom'); });
    await expect(updateTimesheetEntry(baseData(), {}))
      .rejects.toMatchObject({ code: 'internal', message: expect.stringContaining('שגיאה בעדכון רשומת שעתון') });
  });

  test('a thrown HttpsError is rethrown verbatim (not re-wrapped)', async () => {
    checkUserPermissions.mockImplementationOnce(() => { throw new https.HttpsError('unauthenticated', 'לא מחובר'); });
    await expect(updateTimesheetEntry(baseData(), {}))
      .rejects.toMatchObject({ code: 'unauthenticated', message: 'לא מחובר' });
  });
});
